#!/bin/bash
if [ -z "$1" ];then

	echo "usage: $0 sketch.ino"
	exit 1
fi
arduino-cli compile --fqbn arduino:avr:mega $1 && \
arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:mega $1 && \
echo "success" && \
minicom -D /dev/ttyACM0 -b $(cat $1 | grep "^#define BaudRate" | awk '{print $3}')
